// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using symphony.Models;

#nullable disable

namespace symphony.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20251204092459_all")]
    partial class all
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("symphony.Models.course", b =>
                {
                    b.Property<int>("course_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("course_Id"));

                    b.Property<string>("course_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("course_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("course_Id");

                    b.ToTable("tbl_course");
                });

            modelBuilder.Entity("symphony.Models.student", b =>
                {
                    b.Property<int>("student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_Id"));

                    b.Property<string>("student_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("student_age")
                        .HasColumnType("int");

                    b.Property<string>("student_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_Id");

                    b.ToTable("tbl_student");
                });

            modelBuilder.Entity("symphony.Models.teacher", b =>
                {
                    b.Property<int>("teacehr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacehr_id"));

                    b.Property<string>("teacehr_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacehr_gmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("teacher_age")
                        .HasColumnType("int");

                    b.Property<string>("teacher_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("teacher_phone")
                        .HasColumnType("int");

                    b.HasKey("teacehr_id");

                    b.ToTable("tbl_teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
