// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using symphony.Models;

#nullable disable

namespace symphony.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("symphony.Models.admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("admin_id"));

                    b.Property<string>("admin_password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("admin_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("admin_id");

                    b.ToTable("tbl_admin");
                });

            modelBuilder.Entity("symphony.Models.course", b =>
                {
                    b.Property<int>("course_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("course_Id"));

                    b.Property<string>("course_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("course_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("course_Id");

                    b.ToTable("tbl_course");
                });

            modelBuilder.Entity("symphony.Models.coursetopic", b =>
                {
                    b.Property<int>("ct_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ct_id"));

                    b.Property<int>("course_id")
                        .HasColumnType("int");

                    b.Property<string>("ct_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ct_id");

                    b.HasIndex("course_id");

                    b.ToTable("coursetopic");
                });

            modelBuilder.Entity("symphony.Models.student", b =>
                {
                    b.Property<int>("student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_Id"));

                    b.Property<string>("student_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("student_age")
                        .HasColumnType("int");

                    b.Property<string>("student_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_Id");

                    b.ToTable("tbl_student");
                });

            modelBuilder.Entity("symphony.Models.teacher", b =>
                {
                    b.Property<int>("teacehr_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacehr_id"));

                    b.Property<string>("teacher_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("teacher_age")
                        .HasColumnType("int");

                    b.Property<string>("teacher_gmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("teacher_password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("teacher_phone")
                        .HasColumnType("int");

                    b.HasKey("teacehr_id");

                    b.ToTable("tbl_teacher");
                });

            modelBuilder.Entity("symphony.Models.coursetopic", b =>
                {
                    b.HasOne("symphony.Models.course", "course")
                        .WithMany("topics")
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");
                });

            modelBuilder.Entity("symphony.Models.course", b =>
                {
                    b.Navigation("topics");
                });
#pragma warning restore 612, 618
        }
    }
}
